### ISSUE TITLE
make sure mobile/tablet  works

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bit-docs-donejs-theme#25]
![cursor_and_donejs_-_in_depth_guide_and_new_issue_ _donejs_bit-docs-donejs-theme_and_google_software_update](https://cloud.githubusercontent.com/assets/78602/22856097/86de905e-f050-11e6-81be-ca7c17da0193.png)

**Comment by m-mujica** [comment]
missing TOC when hamburger icon is clicked.

![screen shot](https://cloud.githubusercontent.com/assets/724877/22886964/71d234fe-f1bd-11e6-8bd1-6e4372a4cd70.png)
