### ISSUE TITLE
Contribution guide link is incorrect

### ISSUE THREAD

**Issue by m-mujica** [donejs/bit-docs-donejs-theme#32]
Instead of 

```
<li><a href="./contributing.html">Contributing</a></li>
```

it should be 

```
<li><a href="./contribute.html">Contributing</a></li>
```

and in `static.js` the class query should be `body.contribute`. 

![google chrome](https://cloud.githubusercontent.com/assets/724877/23043351/300f6052-f459-11e6-9519-f121757c9629.png)

cc: @chasenlehara

**Comment by chasenlehara** [comment]
That’s incorrect. This is the correct document: https://donejs.com/contributing.html

`contribute.html` is leftover from a document Julia was working on.

**Comment by m-mujica** [comment]
argh, gotcha.... I'm going to remove that old one.
